### ISSUE TITLE
the v2.0 `sites/XXX/datasets` endpoint is returning an `argument list must have even number of elements` error.

### ISSUE THREAD

**Issue by SimonGoring** [NeotomaDB/api_nodetest#68]
Using: `api-dev.neotomadb.org/v2.0/data/sites/2570/datasets` results in the following error:

```
argument list must have even number of elements

error: argument list must have even number of elements
    at Connection.parseE (/net/ceiwww/api-dev.neotomadb.org/node/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/net/ceiwww/api-dev.neotomadb.org/node/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/net/ceiwww/api-dev.neotomadb.org/node/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

The site itself seems to work.

**Comment by SimonGoring** [comment]
Issue is now resolved, and the API for this endpoint is cleaned up.
